import type { Metadata } from 'next';
import Providers from './providers';
import { Layout } from '@/components/layout/layout';
import '@/styles/index.css';

export const metadata: Metadata = {
  title: 'RS React App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <Layout>{children}</Layout>
        </Providers>
      </body>
    </html>
  );
}
