import type { Metadata } from 'next';
import { Suspense } from 'react';
import Providers from './providers';
import { LocaleProvider } from '@/lib/locale-provider';
import { Layout } from '@/components/layout/layout';
import type { ReactNode } from 'react';
import '@/styles/index.css';

export const metadata: Metadata = {
  title: 'RS React App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Suspense fallback={<div>Loading...</div>}>
          <Providers>
            <LocaleProvider>
              <Layout>{children}</Layout>
            </LocaleProvider>
          </Providers>
        </Suspense>
      </body>
    </html>
  );
}
