#!/bin/sh
set -e

blocked=0
while read -r local_ref local_sha remote_ref remote_sha; do
  if [ "$remote_ref" = "refs/heads/main" ]; then
    echo "❌ Push to main is blocked!"
    blocked=1
  fi
done

if [ $blocked -ne 0 ]; then
  exit 1
fi

npm run lint
npm run build
